services:
  mariadb_site2:
    image: mariadb:10.11
    container_name: wordpress_db_site2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SITE2_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SITE2_MYSQL_DATABASE}
      MYSQL_USER: ${SITE2_MYSQL_USER}
      MYSQL_PASSWORD: ${SITE2_MYSQL_PASSWORD}
    volumes:
      - db_data_site2:/var/lib/mysql
    networks:
      - site2_network

  wordpress_site2:
    image: wordpress:${SITE2_WORDPRESS_VERSION}-php${SITE2_PHP_VERSION}-fpm
    container_name: wordpress_site2
    restart: always
    depends_on:
      - mariadb_site2
    environment:
      WORDPRESS_DB_HOST: mariadb_site2:3306
      WORDPRESS_DB_NAME: ${SITE2_WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${SITE2_WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${SITE2_WORDPRESS_DB_PASSWORD}
    volumes:
      - ./html/site2:/var/www/html
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - site2_network

volumes:
  db_data_site2:

networks:
  site2_network:
    external: true
    name: ${SITE2_SHARED_NETWORK}
